### ISSUE TITLE
Página de informações

### ISSUE THREAD

**Issue by lilianecfelix** [CharlesAnjos/gc-issues#3]
Bom criar uma página de informações a respeito do site: objetivos, público, contato.

**Comment by CharlesAnjos** [comment]
deve conter também mapa de localização da empresa e link para chat no whatsapp

**Comment by lilianecfelix** [comment]
Certo, levaremos em consideração.

Em qua., 18 de out. de 2023 às 09:28, Charles Albert Martins dos Anjos <
***@***.***> escreveu:
